{% set name = "selectfasta" %}
{% set version = "2.0" %}
package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/andvides/selectFasta.git
  md5: 243B521C5D6F66C8051E02C08F0A9D9D
  
build:
  noarch: generic
  number: 1

requirements:
  build:
    - {{ compiler('c') }}

test:
  commands:
    - selectFasta -h

about:
  home:  https://github.com/andvides/selectFasta.git
  license: GNU
  summary: "FASTA or FASTQ select from a list of header names"
